# SonarCloud Project Configuration

# Required metadata
sonar.projectKey=Harshit-Choubey_Freelancer_Devops
sonar.organization=harshit-choubey
sonar.projectName=GigMatrix

# Source code location
sonar.sources=src

# Exclusions
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.js,docker/**,docs/**

# Encoding
sonar.sourceEncoding=UTF-8

# Node.js / JavaScript settings
sonar.javascript.lcov.reportPaths=coverage/lcov.info
